parameters:
  cloudflare.api_token: "%env(resolve:CLOUDFLARE_API_TOKEN)%"
  cloudflare.zone_id: "%env(resolve:CLOUDFLARE_ZONE_ID)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Superrb\KunstmaanCdnBundle\:
    resource: "../src/*"
    exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

  Superrb\KunstmaanCdnBundle\Service\ClearCdnCacheService:
    arguments:
      $provider: "%kunstmaan_cdn.provider%"

  Superrb\KunstmaanCdnBundle\Provider\CloudflareProvider:
    lazy: true
    public: true
    arguments:
      $zoneId: "%cloudflare.zone_id%"
